import org.gradle.api.tasks.testing.logging.TestLogEvent

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.3/userguide/tutorial_java_projects.html
 */

plugins {
  // Apply the java plugin to add support for Java
  java

  // Apply the application plugin to add support for building a CLI application.
  application

  antlr
}

repositories {
  mavenLocal()
  mavenCentral()
  jcenter()
}

dependencies {
  // Use ANTLR version 4
  antlr("org.antlr:antlr4:4.7.2")

  // Use JUnit Jupiter API for testing.
  testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

  // Use JUnit Jupiter Engine for testing.
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.2")
}

configure<JavaPluginConvention> {
  sourceCompatibility = JavaVersion.VERSION_1_7
}

group = "me.tomassetti.examples"
version = "1.0"
description = "markup-example"

application {
  // Define the main class for the application.
  mainClassName = "me.tomassetti.examples.MarkupParser.App"
}

tasks {
  val test by getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
    testLogging {
      events(TestLogEvent.PASSED, TestLogEvent.SKIPPED, TestLogEvent.FAILED)
      showStandardStreams = true
    }
  }

  generateGrammarSource {
    maxHeapSize = "64m"
    arguments = arguments + listOf("-visitor", "-long-messages", "-package", "me.tomassetti.examples.MarkupParser")
    outputDirectory = File("$buildDir/generated-src/antlr/main/me/tomassetti/examples/MarkupParser/")
  }
}
